Add pipeline to produce animated gage timeseries in R
usgs-makerspace/gages-through-the-ages pull request #207
Opened 2023-05-14 22:28 UTC by ceenell

Description
-----------
Adding subdirectory to recreate the gage timeseries gif in R with current data. This depends on the `national-flow-observations` output of `active_flow_gages_summary_wy.rds` to be put into `gage_timeseries_gif/data/`. This leans on some of the plotting utils from the `gage_age_gif`, but is in`targets` rather than `scipiper`

Expected output:
![gage-timeseries-optimized](https://github.com/usgs-makerspace/gages-through-the-ages/assets/17803537/ce9689ab-774e-4471-b3c9-2f66d5d9374c)

2023-05-15 17:03 UTC, aaarcher-usgs requested changes
This took 8 minutes to run locally, and created the gif as expected. I don't have gifsicle on my computer, so had to run with `reduce = FALSE`. 

I have some suggestions/questions here and there about the code. I think there are a couple places where some redundant code can be removed, and I noticed a bit of commented-out code throughout that can be removed for cleaning up the pipeline.

2023-05-15 17:03 UTC, aaarcher-usgs commented on gage_timeseries_gif/src/plot_utils.R
> +    #geom_sf(color = 'white', size = 0.2) +
Clean up code throughout by deleting commands that are commented out.

2023-05-17 00:40 UTC, cnell-usgs commented on gage_timeseries_gif/src/map_utils.R
> +  library(dplyr)
yeah totally. didn't catch that when this script was copied over from `gage_age_gif`

2023-05-17 00:43 UTC, cnell-usgs commented on gage_timeseries_gif/src/map_utils.R
> +    # is possible, but filtering to the last one (most recent) for now
I don't follow this. That's an old comment that probably needs to be cleaned up

2023-05-17 00:47 UTC, cnell-usgs commented on gage_timeseries_gif/src/map_utils.R
> +    # is possible, but filtering to the last one (most recent) for now
I'm not totally sure how to interpret it. @lindsayplatt might have some insight on the comment

2023-05-17 00:50 UTC, cnell-usgs commented on gage_timeseries_gif/src/plot_utils.R
> +  active_year <- as.numeric(as.character(yr))
lol

2023-05-17 00:58 UTC, cnell-usgs commented
Suggested edits have been addressed.

2023-05-17 02:18 UTC, aaarcher-usgs approved these changes
Looks good!

2023-05-17 19:56 UTC, merged

2023-05-18 14:10 UTC, lindsayplatt commented on gage_timeseries_gif/src/map_utils.R
> +    # is possible, but filtering to the last one (most recent) for now
Oooo fun edge case - literally!

Those two HUCs are actually right next to each other (see HUC info [here](https://water.usgs.gov/GIS/regions.html)). The big HUC02s represent California (`18`) and the "Great Basin" (`16`), which share a border. If you drill down and look at just those two HUC08s and where the site is, it makes sense that people changed the HUCs depending on the year. Looks like it is right on the border, so either could be true!

<details>
  <summary>Code to make the plot</summary>

```r
library(sf)
library(ggplot2)

huc_2014 <- nhdplusTools::get_huc(id = "18020129", type="huc08")
huc_2016 <- nhdplusTools::get_huc(id = "16050101", type="huc08")
site_loc <- dataRetrieval::readNWISsite("11434500") %>% 
  st_as_sf(coords = c("dec_long_va", "dec_lat_va"), crs=4326)
ggplot() + 
  geom_sf(data=huc_2014, fill="cornflowerblue") + 
  geom_sf(data=huc_2016, fill="salmon") +
  geom_sf(data=site_loc, shape=17, size=3) +
  theme_bw()
```

</details>

![image](https://github.com/usgs-makerspace/gages-through-the-ages/assets/13220910/9dbb839f-1c0d-4069-b968-90c451f83619)